x-server: &default-server
  build: 
      context: ../
      dockerfile: rinha-de-backend-2025-server/Dockerfile
  networks:
      - payment-processor
  environment:
      ASPNETCORE_ENVIRONMENT: Production
      Payments__Default: http://payment-processor-default:8080/
      Payments__Fallback: http://payment-processor-fallback:8080/
      Redis__Connection: redis-server:6379, password=senha123
      Redis__Suffix: rinha_
  depends_on:
      - server-db

services:
  server01:
    <<: *default-server
    ports:
      - 8081:8080

  server02:
    <<: *default-server
    ports:
      - 8082:8080

  server-availability:
    build:
      context: ../
      dockerfile: rinha-de-backend-2025-processor-availability/Dockerfile
    networks:
      - payment-processor
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Payments__Default: http://payment-processor-default:8080/
      Payments__Fallback: http://payment-processor-fallback:8080/
      Redis__Connection: redis-server:6379, password=senha123
      Redis__Suffix: rinha_
    depends_on:
      - redis
      
  server-db:
    image: postgres:17-alpine
    networks:
      - payment-processor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    container_name: server-db
    hostname: server-db
    ports:
      - 54323:5432
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server01
      - server02
    ports:
      - "9999:9999" 
    networks:
      - payment-processor
  
  redis:
    image: redis
    hostname: redis-server
    networks:
      - payment-processor
    ports:
      - 6380:6379
    environment:
      - REDIS_PASSWORD=senha123
    command: redis-server --requirepass senha123
    
networks:
  payment-processor:
    external: true