services:
  redis:
    image: redis
    hostname: redis-server
    # networks:
    #   - backend-network
    ports:
      - 6380:6379
    environment:
      - REDIS_PASSWORD=senha123
    command: redis-server --requirepass senha123
  
  server-db:
    image: postgres:17-alpine
    # networks:
    #   - payment-processor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    container_name: server-db
    hostname: server-db
    ports:
      - 54323:5432